<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="sv" xmlns="http://www.w3.org/1999/xhtml">

<head>
  <title>KWF &gt; <?php echo $title; ?></title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <link type="text/css" title="KWF" href="<?php echo FULLPATH; ?>/css/kwf.min.css" rel="stylesheet" media="screen" />
</head>

<body>

<div id="error-wrapper">
  <h1><?php echo $title; ?></h1>

<?php echo $content_data; ?>
</div>

</body>

</html>