  <p>
    <strong>Meddelande: </strong> <?php echo $exception->getMessage(); ?><br />
    <strong>Fil: </strong> <?php echo $exception->getFile(); ?><br />
    <strong>Rad: </strong> <?php echo $exception->getLine(); ?>
  </p>

  <table>
    <tr>
      <th>Funktion</th>
      <th>Fil</th>
      <th>Rad</th>
      <th>Argument</th>
    </tr>
<?php foreach ($exception->getTrace() as $t): ?>
    <tr>
      <td><?php echo (isset($t['type']) ? $t['type'] . $t['function'] : $t['function']); ?></td>
      <td><?php echo (isset($t['file']) ? $t['file'] : ""); ?></td>
      <td><?php echo (isset($t['line']) ? $t['line'] : ""); ?></td>
      <td><?php (isset($t['file']) ? print_r($t['file'], 1) : ""); ?></td>
    </tr>
<?php endforeach; ?>
  </table>
