<!DOCTYPE html>
<html lang="sv" dir="<?php echo __('READ_DIRECTION'); ?>">

<head>
  <meta charset="utf-8" />
  <title>KWF &gt; <?php echo $title; ?></title>
  <link title="KWF" href="<?php echo FULLPATH; ?>/css/site<?php if (MINIFIED) echo '.min'; ?>.css" rel="stylesheet" media="screen" />
  <link href="<?php echo FULLPATH; ?>/css/site_print<?php if (MINIFIED) echo '.min'; ?>.css" rel="stylesheet" media="print" />
  <!--<link type="image/vnd.microsoft.icon" href="<?php echo FULLPATH; ?>/favicon.ico" rel="icon" />-->
<?php if (MINIFIED): ?>
  <script src="<?php echo FULLPATH; ?>/js/site.min.js"></script>
<?php else: ?>
  <script src="<?php echo FULLPATH; ?>/js/kwf.js"></script>
  <script src="<?php echo FULLPATH; ?>/js/kwf.Widget.js"></script>
  <script src="<?php echo FULLPATH; ?>/js/site.js"></script>
<?php endif; ?>
  <!--[if lte IE 8]><script src="<?php echo FULLPATH; ?>/js/html5.min.js" type="text/javascript"></script><![endif]-->
  <?php scriptLanguageExport(); ?>
</head>

<body>

<header id="header">
  <h1 id="logo"><a href="<?php echo urlModr(); ?>">KWF</a></h1>

  <nav id="menu">
    <ul>
      <li><a href="<?php echo urlModr(); ?>" class="content-context"><?php echo __('HEADER_HOME'); ?></a></li>
      <li><a href="<?php echo urlModr('kontakt'); ?>" class="content-context"><?php echo __('HEADER_CONTACT'); ?></a></li>
      <li><a href="<?php echo urlModr('ladda-upp'); ?>" class="content-context"><?php echo __('HEADER_UPLOAD'); ?></a></li>
    </ul>
  </nav>
</header>

<ul id="kwf_messages_view">
<?php foreach ($error_messages as $msg): ?>
  <li class="kwf-error"><?php echo $msg; ?></li>
<?php endforeach;

foreach ($info_messages as $msg): ?>
  <li class="kwf-info"><?php echo $msg; ?></li>
<?php endforeach; ?>
</ul>

<div id="content">

<?php echo $content_data; ?>

</div>

<footer id="footer">
  <p><?php echo __('FOOTER_COPYRIGHT', '<a href="http://kekos.se/">Christoffer Lindahl</a>', '2009-2013'); ?></p>
</footer>

</body>

</html>