<!DOCTYPE html>
<html lang="sv" dir="<?php echo _('READ_DIRECTION'); ?>">

<head>
  <title>KWF &gt; <?php echo $this->title; ?></title>
  <meta charset="utf-8" />
  <link title="KWF" href="<?php echo FULLPATH; ?>/css/kwf<?php if (MINIFIED) echo '.min'; ?>.css" rel="stylesheet" media="screen" />
  <link href="<?php echo FULLPATH; ?>/css/site_print<?php if (MINIFIED) echo '.min'; ?>.css" rel="stylesheet" media="print" />
  <!--<link type="image/vnd.microsoft.icon" href="<?php echo FULLPATH; ?>/favicon.ico" rel="icon" />-->
<?php if (MINIFIED): ?>
  <script src="<?php echo FULLPATH; ?>/js/site.min.js"></script>
<?php else: ?>
  <script src="<?php echo FULLPATH; ?>/js/kwf.js"></script>
  <script src="<?php echo FULLPATH; ?>/js/site.js"></script>
<?php endif; ?>
  <!--[if lte IE 8]><script src="<?php echo FULLPATH; ?>/js/html5.min.js" type="text/javascript"></script><![endif]-->
</head>

<body>

<header id="header">
  <h1><a href="<?php echo urlModr(); ?>">KWF</a></h1>
</header>

<nav id="menu">
  <ul>
    <li><a href="<?php echo urlModr(); ?>" class="clink"><?php echo _('HEADER_HOME'); ?></a></li>
    <li><a href="<?php echo urlModr('kontakt'); ?>" class="clink"><?php echo _('HEADER_CONTACT'); ?></a></li>
    <li><a href="<?php echo urlModr('ladda-upp'); ?>" class="clink"><?php echo _('HEADER_UPLOAD'); ?></a></li>
    <li><a href="<?php echo urlModr('internal-redirect'); ?>" class="clink"><?php echo _('HEADER_REDIRECT'); ?></a></li>
  </ul>
</nav>

<div id="content">
<?php if (count($this->error_messages)): ?>
  <ul id="errorlist">
<?php foreach ($this->error_messages as $msg): ?>
    <li><?php echo $msg; ?></li>
<?php endforeach; ?>
  </ul>
<?php endif; 

if (count($this->info_messages)): ?>
  <ul id="infolist">
<?php foreach ($this->info_messages as $msg): ?>
    <li><?php echo $msg; ?></li>
<?php endforeach; ?>
  </ul>
<?php endif; ?>

<?php echo $this->content_data; ?>

</div>

<footer id="footer">
  <p><?php echo _('FOOTER_COPYRIGHT', '<a href="http://kekos.se/">Christoffer Lindahl</a>', '2009-2012'); ?></p>
</footer>

</body>

</html>