  <section class="third-section" id="UploadController">
    <h1><?php echo __('UPLOAD_HEADER_UPLOAD'); ?></h1>

    <form action="<?php echo urlModr($route); ?>" method="post" enctype="multipart/form-data" id="upload_form">
      <fieldset>
        <ol>
          <li><label for="file"><?php echo __('UPLOAD_FILE'); ?></label> <input type="file" name="file" id="file" multiple="multiple" /></li>
          <li><button type="submit" name="upload" value="yes"><?php echo __('UPLOAD_SEND'); ?></button></li>
        </ol>
      </fieldset>
    </form>
  </section>

  <section class="third-section">
    <h1><?php echo __('UPLOAD_HEADER_UPLOADED'); ?></h1>

    <ul id="upload_list_view">
<?php foreach ($uploads as $file):
if ($file != '..' && $file != '.'):

$file = htmlspecialchars($file);

require('uploaded-file.phtml');

endif;
endforeach; ?>
    </ul>
  </section>

  <section class="third-section">
    <p id="upload_datetime" data-url="<?php echo urlModr($route, 'datetime'); ?>"><?php echo __('UPLOAD_LAST_UPDATE', date(__('DATETIME_FORMAT') . ':s')); ?></p>
  </section>

  <div class="clear"></div>
