  <div class="pure-g-r">
    <section class="pure-u-1-3" id="UploadController">
      <h1><?php echo __('UPLOAD_HEADER_UPLOAD'); ?></h1>

      <form action="<?php echo urlModr($route); ?>" method="post" enctype="multipart/form-data" id="upload_form" class="pure-form">
        <label for="file"><?php echo __('UPLOAD_FILE'); ?></label>
        <input type="file" name="file" id="file" multiple="multiple" />

        <button type="submit" name="upload" value="yes" class="pure-button"><?php echo __('UPLOAD_SEND'); ?></button>
      </form>
    </section>

    <section class="pure-u-1-3">
      <h1><?php echo __('UPLOAD_HEADER_UPLOADED'); ?></h1>

      <ul id="upload_list_view">
<?php foreach ($uploads as $file):
if ($file != '..' && $file != '.'):

$file = htmlspecialchars($file);

require('uploaded-file.phtml');

endif;
endforeach; ?>
      </ul>
    </section>

    <section class="pure-u-1-3">
      <p id="upload_datetime" data-url="<?php echo urlModr($route, 'datetime'); ?>"><?php echo __('UPLOAD_LAST_UPDATE', date(__('DATETIME_FORMAT') . ':s')); ?></p>
    </section>

  </div>
